# Generated by Django 5.2.6 on 2025-09-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagaEmprego', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='vaga',
            old_name='created_at',
            new_name='criado_em',
        ),
    ]
