# Generated by Django 5.2.6 on 2025-11-03 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagaEmprego', '0003_rename_criado_em_candidato_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaga',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
